### ISSUE TITLE
Poincare Duality

### ISSUE THREAD

**Issue by kijouneli** [opengeospatial/IndoorGML-SWG#3]
- The current data model is based on Poincare Duality (PD) which requires any two cell spaces to share the boundary surface to make the edge between them. In some cases, such as visibility graph or POI, it is not easy to find the common boundary surfaces and consequently not easy to make the edges. 
- This observation leads to the following questions 
 1) Do we need to keep the PD in IndoorGML 2
 2) If we may keep the PD, is there any way to allow to set an edge between two cell spaces that are not sharing boundary surfaces?

**Comment by abdoulayediak** [comment]
PD is indeed restricting for some types of graphs that are still widely used in navigation. For example, the current version of IndoorGML, as well as the draft of version 2.0 do not allow the visibility graph (in yellow) in the image below to be represented in the dual space.
<p align="center">
<img src="https://user-images.githubusercontent.com/7335122/178487255-e76bee2f-6810-4f70-967e-6421b504cde6.png" width="400"/>
</p>

The issue has been brought to a SWG discussion and it was decided the following:

1. We can certainly keep PD as it provides a strong background for navigation scenarios where adjacency (geometric) network are needed, but we also need to accommodate other types of networks. 
2. The most straightforward way to do so is to lift the CellBoundary constraint of the Edge class of the Dual Space in IndoorGML 2.0. The current cardinality of that relationship is set to 1, meaning that any Edge of the Dual Space needs to be linked to a CellBoundary in the Primal space. 

<p align="center">
<img src="https://user-images.githubusercontent.com/7335122/178490503-c7100fbb-3d72-44cc-ae23-1b734688418d.png" width="500"/>
</p>

By setting that cardinality to **0..1**, it becomes possible to skip such constraint for logical networks that need to cross several CellSpaces (e.g. visibility graphs).
