### ISSUE TITLE
Some minor typos in version 1.1

### ISSUE THREAD

**Issue by ghobona** [opengeospatial/IndoorGML-SWG#4]
**Clause 9.8**

The second paragraph says "The NavigableBoundary class has a subclass, called TrasferBoundary." 

TrasferBoundary should have been TransferBoundary.

**Clause 9.13**

The first paragraph says “It also has association relation with Transition class in the Indoor Core Module, which named to referencedTrasition element.” 

referencedTrasition should have been referencedTransition. 

**Figure 23** 

There are two issues spotted on the figure.

The figure shows a class called “TrasitionSpace”.  This is a typo and should have been “TransitionSpace”.

The figure also shows a class called “TrasferSpace”.  This is a typo and should have been “TransferSpace”.

See the attached screenshot below.

![Screenshot 2022-07-04 at 15 20 09](https://user-images.githubusercontent.com/18121038/177203760-350d3a2d-d056-49ca-ad69-3b1afc879776.png)

**Comment by kijouneli** [comment]
Thanks a lot for this correction. Actually, we need more eyes to make it complete. We will try to make a corrigendum (1.1.1) and check the 2.0 whether it was copied to 2.0 as well.  And at the next meeting on July 12 (or 13 depending on where you are), I'd brielfly mention it.

**Comment by kijouneli** [comment]
Has to be reflected to corrigendum
