### ISSUE TITLE
Different cardinalities between primal and dual spaces (Figure 16)

### ISSUE THREAD

**Issue by kijouneli** [opengeospatial/IndoorGML-SWG#6]
As the following figure (a part of Figure 16), Node and Edge are the dualities of CellSpace and CellBoundary respectively. But the cardinalities are different between primal space and dual space. Why don't we make them consistent?
![image](https://user-images.githubusercontent.com/6386983/179732300-a876d9ae-c25c-46de-9911-debfcb00deed.png)

**Comment by abdoulayediak** [comment]
This cardinality is based on the following principle: 

- Not all CellSpace/CellBoundary instances are associated with Node/Edge instances. 
- All Node/Edge instances are associated with CellSpace/CellBoundary instances.

This is to account for cases where the dual space is needed for a part of a given model only. For example, a multi-storey building can have all its spaces represented in the primal space, but a network (dual space) may be only needed for one of the storeys. Therefore, CellSpace/Cellboundary instances of that storey will have corresponding dual entities but not the rest.

Hope this helps clarifying.

**Comment by kijouneli** [comment]
Clarified
